### ISSUE TITLE
cannnot download the ready-made demo

### ISSUE THREAD

**Issue by cuijiaxu** [markolofsen/metaplugin-pixel-streaming#1]
hi, 
   I tried to download this demo, but failed.
   [Download a ready-made project for Unreal Engine](https://metapublic.s3.amazonaws.com/CarConfigurator.zip)

  `This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AllAccessDisabled</Code>
<Message>All access to this object has been disabled</Message>
<RequestId>4Y5K9WWKFSC86FT3</RequestId>
<HostId>qUmGnW8fWfJd4pPMbLrTTIosW97wVfofo3hI17eGGRZx+0/0n+eLUPdBDI52+OIyYXChMIgziS4=</HostId>
</Error>
data:text/css,html,body,a,div,p,img,textarea{-webkit-touch-callout:text !important;-webkit-user-select:text !important;user-select:text !important;}`

**Comment by markolofsen** [comment]
@cuijiaxu try again please
